package com.kmkbe.modules.loan_submission.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.kmkbe.core.utils.ObjectUtils;
import com.kmkbe.core.domain.entity.Customer;
import com.kmkbe.modules.customer.utils.CustomerUtils;
import com.kmkbe.core.domain.dto.LoanSubmissionSessionDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;

import java.security.SignatureException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Optional;

@Service
//@RequiredArgsConstructor
@Slf4j
public class SessionLoanSubmissionService {
    private final JdbcTemplate jdbcTemplate;

    public SessionLoanSubmissionService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        initTbl();
    }

    private void initTbl() {
        final String query =
                "select count(*) "
                        + "from information_schema.tables "
                        + "where table_name = ? and table_schema = 'public'";

        Integer result = jdbcTemplate.queryForObject(query, Integer.class, "_loan_submission_session");
        if (result == null || result == 0) {
            final String createTable =
                    """
                                create table public._loan_submission_session
                                (
                                    id                          int generated by default as identity primary key,
                                    cust_code uuid not null,
                                    last_step int default 0 not null,
                                    session json null,
                                    dtm_crt                     timestamp default now()          not null,
                                    dtm_upd                     timestamp default now()          not  null
                                );
                            """;

            jdbcTemplate.execute(createTable);
        }
    }

    public LoanSubmissionSessionDto create(
            Authentication authentication,
            int lastStep,
            Object jsonSession
    ) throws SignatureException, JsonProcessingException {
        try {
            Customer customer = CustomerUtils.authenticateCustomer(authentication);
            Optional<LoanSubmissionSessionDto> find = findLastByCust(customer);

            final LoanSubmissionSessionDto result;
            if (find.isEmpty()) {
                jdbcTemplate.update(
                        "insert into public._loan_submission_session (cust_code, last_step, session, dtm_crt) values (?, ?, ?, ?)",
                        customer.getCustCode(),
                        lastStep,
                        ObjectUtils.jsonToStr(jsonSession),
                        Timestamp.from(Instant.now())
                );
            } else {
                jdbcTemplate.update(
                        "update public._loan_submission_session set last_step = ?, session = ?, dtm_upd = ? where cust_code = ?",
                        lastStep,
                        ObjectUtils.jsonToStr(jsonSession),
                        Timestamp.from(Instant.now()),
                        customer.getCustCode()
                );
            }

            result = findLastByCust(customer).get();

            return result;
        } catch (Exception e) {
            log.error("create: error {}", e.getMessage());
            throw e;
        }
    }

    public Optional<LoanSubmissionSessionDto> findLastByCust(Customer customer) {
        try {
            LoanSubmissionSessionDto result = jdbcTemplate.queryForObject(
                    "select cust_code, last_step, session, dtm_crt, dtm_upd from public._loan_submission_session where cust_code = ? order by id desc limit 1",
                    (rs, rowNum) -> LoanSubmissionSessionDto.builder()
                            .lastStep(rs.getInt("last_step"))
                            .dtmCrt(Instant.ofEpochMilli(rs.getTimestamp("dtm_crt").getTime()))
                            .dtmUpd(rs.getTimestamp("dtm_upd") != null ? Instant.ofEpochMilli(rs.getTimestamp("dtm_upd").getTime()) : null)
                            .session(ObjectUtils.strToJson(rs.getString("session")))
                            .build(),
                    customer.getCustCode()
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException emptyResultDataAccessException) {
            return Optional.empty();
        } catch (Exception e) {
            log.error("findLastByCust, error {}", e.getMessage());
            throw e;
        }
    }
}
