spring.application.name=kmkbe
spring.mvc.static-path-pattern=/static/**
spring.jackson.deserialization.adjust-dates-to-context-time-zone=true
#server.address=0.0.0.0
server.port=8443

#server.port=80
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
security.jwt.expiration-time=3000000
jwt.refreshExpirationDateInMs=9000000
security.jwt.secret-key=84b6e04f3268b78e7fee1883733e47aff50b88d1184b3512f2b5bffadb99d7eb
security.api.key=$2b$10$YoLl0SFxCMlIWXfQ9RhixeU8Vxvj9Fi7RmF5j7zA9dhYwdplSGyWC
security.secret-key=DFA42k6CEhLSiX6o1zIPWUlzQGezQfHH

# Path untuk reports
jasper.report.dir=classpath:/reports/

# Handle font
net.sf.jasperreports.awt.ignore.missing.font=true


management.endpoints.web.base-path=/api/monitoring
management.endpoint.health.show-details=never
management.endpoint.health.show-components=always
management.endpoints.web.exposure.include=info, health, logfile, loggers, env
#management.endpoints.web.cors.allow-credentials=true
management.endpoint.logfile.external-file=admin.log

spring.profiles.active=dev


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
# --- Nonaktifkan auto konfigurasi Redis & MongoDB ---

