# region db env
#spring.datasource.url=jdbc:postgresql://db-kmk.cc6z1g8cfqcv.ap-southeast-3.rds.amazonaws.com:5432/kmkds?stringtype=unspecified
spring.datasource.url=jdbc:postgresql://aurora-kmk.cluster-cc6z1g8cfqcv.ap-southeast-3.rds.amazonaws.com:5432/kmkds?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=Csultmt10
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.flyway.locations=classpath:db/migration/dev/{vendor}
spring.flyway.schemas=public
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
#spring.flyway.table=fly_way
# endregion


# region db log env
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=kmklog
spring.data.mongodb.collection=event
# endregion

# region caching
spring.cache.type=redis
#spring.cache.redis.time-to-live=60000
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=6
spring.data.redis.password=
#spring.data.redis.timeout=6000
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=30
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
#spring.data.redis.lettuce.shutdown-timeout=1000
spring.data.redis.lettuce.pool.max-wait=10000
# endregion

# region api-docs
springdoc.paths-to-match=/api/v1/**
springdoc.swagger-ui.path=/api/v1/swagger-ui.html
springdoc.api-docs.path=/api/v1/api-docs
# endregion

# region dev tools
logging.file.name=./logs/log-file.log
logging.logback.rollingpolicy.clean-history-on-start=true
logging.logback.rollingpolicy.max-file-size=10MB
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type=trace
logging.level.org.hibernate.stat=debug

server.error.whitelabel.enabled=false

spring.boot.admin.client.url=http://localhost:9000
spring.boot.admin.client.instance.name=Kmk-Digital-2.0
spring.boot.admin.client.username=vandikalvandi@gmail.com
spring.boot.admin.client.password=12345
# endregion

# region testing mail env
testing.mail.host=smtp.gmail.com
testing.mail.port=587
testing.mail.username=khesa.oto@gmail.com
testing.mail.password=tfru zmuk gtfb mrsz
# endregion

# region oauth2 certs
rsa.private-key=classpath:certs/pkcs8.pem
rsa.public-key=classpath:certs/public-key.pem
# endregion

# region Internal Csul URL
csul.sisca.v1.internal=http://10.30.15.146:8185/SISCAConnect/api/v1
csul.sisca.v1.white-list=http://10.30.15.146:8185/SISCAConnect/api/v1
csul.sisca.v1.auth.username=KMKDigital
csul.sisca.v1.auth.password=CSUljkt#2024
#csul.confins.fou.v1=https://internal-csul-prod-private-479341237.ap-southeast-3.elb.amazonaws.com/api/fou/v1
#csul.confins.mou.v1=https://internal-csul-prod-private-479341237.ap-southeast-3.elb.amazonaws.com/api/mou/v1
#csul.confins.los.v1=https://internal-csul-prod-private-479341237.ap-southeast-3.elb.amazonaws.com/api/los/v1

#csul.confins.fou.v1=https://a6ebe04d0a9f743a2a646fd0732267ea-acd5a910eb90c386.elb.ap-southeast-3.amazonaws.com/api/fou/v1
#csul.confins.mou.v1=https://a6ebe04d0a9f743a2a646fd0732267ea-acd5a910eb90c386.elb.ap-southeast-3.amazonaws.com/api/mou/v1
#csul.confins.los.v1=https://a6ebe04d0a9f743a2a646fd0732267ea-acd5a910eb90c386.elb.ap-southeast-3.amazonaws.com/api/los/v1

#csul.mst.v1=https://6mn45m67ybarmii47vg4cc22240ltnmj.lambda-url.ap-southeast-1.on.aws/v1
csul.mst.v1=https://goakcwwrshxfwkgm6bwnegpeti0ajaus.lambda-url.ap-southeast-1.on.aws/v1

csul.confins.adinskey=QXMwZjF0VWVOc1BOTER4T2xKcGZhbnkvSk5kS3dYR2M3NVI3WGJLTDlCOFNZUz0=
env=dev

csul.confins.fou.v1=https://confins.csulfinance.com/api/fou/v1
csul.confins.mou.v1=https://confins.csulfinance.com/api/mou/v1
csul.confins.los.v1=https://confins.csulfinance.com/api/los/v1
csul.confins.ar.v1=https://confins.csulfinance.com/api/ar/v1
csul.confins.payment.v1=https://confins.csulfinance.com/api/payment/v1

# endregion

aspect.enabled=true
