spring.application.name=kmkbe
spring.mvc.static-path-pattern=/static/**
spring.jackson.deserialization.adjust-dates-to-context-time-zone=true
server.port=8080

# db env
spring.datasource.url=jdbc:postgresql://db-kmk.cc6z1g8cfqcv.ap-southeast-3.rds.amazonaws.com:5432/kmkds
spring.datasource.username=postgres
spring.datasource.password=Csultmt10
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.flyway.locations=classpath:db/migration/prod/{vendor}
spring.flyway.schemas=public
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
#spring.flyway.table=fly_way
# db env

# db log env
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=kmklog
spring.data.mongodb.collection=event
# db log env

# caching
redis.host=localhost
redis.port=6379
# caching

# jwt env
security.jwt.secret-key=98d8710219d8224094b7fcb956c054f15d633ad1dfd18d42fdd7f59d77d69f69
security.jwt.expiration-time=1800000
# jwt env

# api-docs
springdoc.paths-to-match=/api/**
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
# api-docs

# Internal Csul URL
csul.sisca.v1.internal=http://10.30.15.146:8185/SISCAConnect/api/v1
csul.sisca.v1.white-list=http://103.165.221.181:8185/SISCAConnect/api/v1
csul.sisca.v1.auth.username=KMKDigital
csul.sisca.v1.auth.password=CSUljkt#2024
# Internal Csul URL

# dev tools
#logging.level.org.hibernate=ERROR
#logging.level.org.springframework.web=ERROR
#logging.level.root=INFO
logging.file.name=./logs/log-file.log
server.error.whitelabel.enabled=false
management.endpoints.web.exposure.include=info, health, logfile, loggers, env
management.endpoints.web.cors.allow-credentials=true
management.endpoint.health.show-details=always
management.endpoint.logfile.external-file=admin.log
#management.info.env.enabled=true
#management.endpoints.web.base-path=/monitoring
spring.boot.admin.client.url=http://localhost:9000
spring.boot.admin.client.instance.name=Kmk-Digital-2.0
spring.boot.admin.client.username=vandikalvandi@gmail.com
spring.boot.admin.client.password=12345
# dev tools

aspect.enabled=true
