env: local
spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
        instance:
          name: Kmk-Digital-2.0
        credentials:
          username: vandikalvandi@gmail.com
          password: 12345
  datasource:
    url: jdbc:postgresql://aurora-kmk.cluster-cc6z1g8cfqcv.ap-southeast-3.rds.amazonaws.com:5432/kmkds?stringtype=unspecified
    username: postgres
    password: Csultmt10
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kmklog
    redis:
      host: localhost
      port: 6379
      database: 6
      password:
      timeout: 6000
      lettuce:
        pool:
          enabled: true
          max-active: 30
          max-idle: 10
          min-idle: 2
          shutdown-timeout: 1000
          max-wait: 10000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/dev/{vendor}
    schemas: public
    enabled: true
    baseline-on-migrate: true

  cache:
    type: redis
    redis:
      time-to-live: 60000

  mail:
    host: nikita.co.id
    port: 465
    protocol: smtp
    username: csul@nikita.co.id
    password: DArS!OP#csul6?6Uu
    properties:
      mail.smtp.ssl.trust: '*'
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# region testing mail env
testing:
    mail:
      host: nikita.co.id
      port: 465
      protocol: smtp
      username: csul@nikita.co.id
      password: DArS!OP#csul6?6Uu

# Keep your custom collection property anywhere you like
custom:
  mongodb:
    collection: event

jwt:
  env:
    security:
      jwt:
        secret-key: 98d8710219d8224094b7fcb956c054f15d633ad1dfd18d42fdd7f59d77d69f69
        expiration-time: 1800000

spring-doc:
  version: '3.0'
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


    logging:
      file: ./logs/log-file.log
      level:
        org.hibernate: ERROR
        org.springframework.web: ERROR
        root: INFO
server:
  error:
    whitelabel:
      enabled: false

rsa:
  private-key: classpath:certs/pkcs8.pem
  public-key: classpath:certs/public-key.pem


csul:
  sisca:
    v1:
      internal: http://10.30.15.146:8185/SISCAConnect/api/v1
      white_list: http://10.30.15.146:8185/SISCAConnect/api/v1
      auth:
        username: KMKDigital
        password: CSUljkt#2024
  mst:
    v1: http://goakcwwrshxfwkgm6bwnegpeti0ajaus.lambda-url.ap-southeast-1.on.aws/v1
  confins:
    adinskey: VlBJZllVQTZyUk5acW9FQVg3Yk9oSTlLT1lsRWUzMkllU1ZlZVZtaTExZ1NZUz0=
    fou:
      v1: http://uat-confinsr3.csulfinance.com/api/fou/v1
      getzipcode: http://172.21.10.149:8083/fou_getzipcode.php
      getcalculate: http://172.21.10.149:8083/fou_getcalculate.php
    mou:
      v1: http://uat-confinsr3.csulfinance.com/api/mou/v1
      getcwrbwhr: http://172.21.10.149:8083/mou_getcwrbouwheer.php
      getlistcwrbwhr: http://172.21.10.149:8083/mou_getlistcwrbwhr.php
      getpagingSQL: http://172.21.10.149:8083/mou_getpagingsql.php
      fwd: http://172.21.10.149:8083/mou_getsigner.php
    #LOS
    los:
      v1: http://uat-confinsr3.csulfinance.com/api/los/v1
      fwd: http://172.21.10.149:8083/los_getagr.php
      getRekening: http://172.21.10.149:8083/los_getrekening.php
      getAppNo: http://172.21.10.149:8083/los_getappno.php
      getpagingSQL: http://172.21.10.149:8083/los_getpagingsql.php
    #CORELOS
    corelos:
      v1: http://uat-confinsr3.csulfinance.com/api/corelos/v1
      getFinData: http://172.21.10.149:8083/corelos_getfindata.php
      getFactoring: http://172.21.10.149:8083/corelos_getfactoring.php

    ar:
      v1: http://uat-confinsr3.csulfinance.com/api/ar/v1
    payment:
      v1: http://uat-confinsr3.csulfinance.com/api/payment/v1
    ap:
      v1: http://uat-confinsr3.csulfinance.com/api/ap/v1
  ckb :
    url:
    api-key:
aspect:
  enabled: true

app:
  api:
    key: YiByHB@CSUL_DEV

# Feign Configuration
feign:
  csul:
    ckb:
      url: https://api-ckbvendorportal.dipstrategy.co.id
      username: ramco
      password: RamcoVDC2026!
      client-secret: SecretRamco2026!

  confins:
    url: https://uat-confinsr3.csulfinance.com
    adins-key: VlBJZllVQTZyUk5acW9FQVg3Yk9oSTlLT1lsRWUzMkllU1ZlZVZtaTExZ1NZUz0=