spring.application.name=kmkbe
spring.mvc.static-path-pattern=/static/**
spring.jackson.deserialization.adjust-dates-to-context-time-zone=true
server.port=8443
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
security.jwt.secret-key=84b6e04f3268b78e7fee1883733e47aff50b88d1184b3512f2b5bffadb99d7eb
security.jwt.expiration-time=300000
jwt.refreshExpirationDateInMs=9000000
security.api.key=39d67cb62399fddc455c535de4b5209c
spring.profiles.active=dev
