CREATE TABLE IF NOT EXISTS public._loan_submission_session
(
    id int generated by default as identity primary key,
    cust_code uuid not null,
    last_step int default 0 not null,
    session json null,
    dtm_crt timestamp default now() not null,
    dtm_upd timestamp default now() not null
);

CREATE TABLE IF NOT EXISTS public._existing_customer
(
    id int generated by default as identity primary key,
    vendor_code varchar(50) not null,
    is_existing boolean default false not null,
    identity_type varchar(20) not null,
    identity_no varchar(50) not null,
    dtm_crt timestamp default now() not null,
    dtm_upd timestamp default null
);

CREATE TABLE IF NOT EXISTS public._refresh_token
(
    id int generated by default as identity primary key,
    user_code uuid not null,
    refresh_token uuid not null,
    expired_date timestamp without time zone not null,
    issued_date timestamp without time zone default current_timestamp
);

CREATE TABLE IF NOT EXISTS public._loan_important_notes
(
    id int generated by default as identity primary key,
    vendor_code varchar(255) not null,
    bouwheer_code varchar(255) not null,
    already_accept_important_notes boolean default false not null,
    dtm_crt timestamp not null
);
