package com.kmkbe.modules.customer.service.refresh_token;

import com.kmkbe.modules.customer.entity.Customer;
import com.kmkbe.modules.customer.model.RefreshToken;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.Optional;
import java.util.UUID;

@Service("DbRefreshTokenServices")
@Slf4j
public class DbRefreshTokenServices implements IRefreshTokenServices {
    private final JdbcTemplate jdbcTemplate;

    public DbRefreshTokenServices(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        init();
    }

    private void init() {
        String createTable =
                """
                            create table _refresh_token
                            (
                                id                         int generated by default as identity primary key,
                                cust_code                  uuid                        not null,
                                refresh_token              uuid                        not null,
                                expired_date timestamp without time zone not null,
                                issued_date               timestamp without time zone default current_timestamp
                            );
                        """;

        jdbcTemplate.execute("drop table if exists _refresh_token");
        jdbcTemplate.execute(createTable);
    }

    @Override
    public RefreshToken create(Customer customer) {
        try {
            final RefreshToken payload = defaultPayload(customer);

            jdbcTemplate.update(
                    "insert into public._refresh_token (cust_code, refresh_token, expired_date) values (?, ?, ?)",
                    payload.getCustCode(),
                    payload.getRefreshToken(),
                    payload.getExpiredDate()
            );

            return payload;
        } catch (Exception e) {
            log.error("DB create, error {}", e.getMessage());
            throw e;
        }
    }

    @Override
    public Boolean invalidate(String refreshToken) {
        try {
            int result = jdbcTemplate.update(
                    "delete from public._refresh_token where refresh_token = ?",
                    refreshToken
            );

            return result > 0;
        } catch (Exception e) {
            log.error("DB invalidate, error {}", e.getMessage());
            throw e;
        }
    }

    @Override
    public RefreshToken verify(String refreshToken) {
        try {
            RefreshToken last = findBy("refresh_token", refreshToken)
                    .orElseThrow(() -> new RuntimeException("Refresh token not found"));

            if (last.getExpiredDate().before(new Date())) {
                throw new IllegalStateException("Refresh token are expired or invalid, try to login again");
            }

            return last;
        } catch (Exception e) {
            log.error("DB verify, error {}", e.getMessage());
            throw e;
        }
    }

    private Optional<RefreshToken> findBy(String column, String value) {
        try {
            return Optional.ofNullable(jdbcTemplate.queryForObject(
                    "select cust_code, refresh_token, expired_date, issued_date from public._refresh_token where " + column + " = ? order by id desc limit 1",
                    (rs, rowNum) -> {
                        RefreshToken refreshToken = new RefreshToken();
                        refreshToken.setCustCode(rs.getObject("cust_code", UUID.class));
                        refreshToken.setRefreshToken(rs.getObject("refresh_token", UUID.class));
                        refreshToken.setExpiredDate(rs.getTimestamp("expired_date"));
                        refreshToken.setIssuedDate(rs.getTimestamp("issued_date"));
                        return refreshToken;
                    },
                    value
            ));
        } catch (EmptyResultDataAccessException emptyResultDataAccessException) {
            return Optional.empty();
        } catch (Exception e) {
            log.error("findBy, error {}", e.getMessage());
            throw e;
        }
    }
}
